
name = "§o§l§aNewb Santan Revitalized"
version = [0, 2, 0]
min_supported_mc_version = [1, 21, 20]
description = '''
§c%w
§fAdding clarity to MCBE graphics.
%v
§3https://github.com/KianSantan88/nx-santan-shader
''' # %w = patch warning, %v = version
authors = ["raden1", "devendrn"]
url = "https://github.com/KianSantan88/nx-santan-shader"
uuid = "d89d0f2d-2af6-4afb-a36c-ee116d25f16f" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]

[info] 
copyright = '''
Copyright © 2025 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
''' # %a = authors
credits = '''
better realistic clouds code: amg
new end-sky & black hole: firmw4 / shou
fake bloom through textures: Ale or rexytmc
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "HIGH_REALISTIC_CLOUDS"
materials = ["Clouds", "RenderChunk", "Sky", "EndSky"]
description = '''
§4High (realistic clouds)
Realistic-ish clouds and the usual.
'''

[[subpack]]
define = "HIGH_ROUNDED_CLOUDS"
materials = ["Clouds", "RenderChunk", "Sky", "EndSky"]
description = '''
§4High (rounded clouds)
Multilayer 16 steps Rounded Clouds
Folliage waves
Glow leaks and Shimmer
'''

[[subpack]]
define = "HIGH_BOX_CLOUDS"
materials = ["Clouds", "RenderChunk", "Sky", "EndSky"]
description = '''
§4High (box clouds)
Multilayer Box Clouds
Folliage waves
Glow leaks and Shimmer
'''


[[subpack]]
define = "MEDIUM_REALISTIC_CLOUDS"
materials = ["Clouds", "RenderChunk", "Sky", "EndSky"]
description = '''
§eMedium (realistic clouds)
Realistic-ish clouds
No Folliage waves
No Glow and Shimmer
'''


[[subpack]]
define = "MEDIUM_BOX_CLOUDS"
materials = ["Clouds", "RenderChunk", "Sky", "EndSky"]
description = '''
§eMedium (box clouds)
Box Clouds
No Folliage Waves
No Glow and Shimmer
'''

[[subpack]]
define = "MEDIUM_ROUNDED_CLOUDS"
materials = ["Clouds", "RenderChunk", "Sky", "EndSky"]
description = '''
§eMedium (rounded clouds)
Rounded Clouds
No Folliage Waves
No Glow and Shimmer
'''

[[subpack]]
define = "MEDIUM_ROUNDED_CLOUDS_NO_AURORA"
materials = ["Clouds", "RenderChunk", "Sky", "EndSky"]
description = '''
§eMedium (rounded clouds)
Rounded Clouds
No Aurora
No Folliage Waves 
No Glow and Shimmer
'''

[[subpack]]
define = "LITE"
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]
description = '''
§aLite (soft clouds)
Many effects disabled. A bit lighter!
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
'''
