name = "Newb Santan Revitalized"
version = [0, 1, 0]
min_supported_mc_version = [1, 21, 20]
description = '''
§c%w
§7- §aA Newb edit with spectacular colors and more subtle tweaks!
%v
https://discord.com/channels/844591537430069279/1301209950340518011
''' # %w = patch warning, %v = version
authors = ["raden1", "devendrn"]
url = "https://devendrn.github.io/newb-shader/"
<<<<<<< HEAD
uuid = "2814ec5e-9c0d-406d-a162-01b333018de3" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "LegacyCubemap", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]
=======
uuid = "95f774cf-4afa-73e7-a21a-72146307b1d2" # Use https://www.uuidgenerator.net/version4
>>>>>>> a69099e83ce7387404bfb6494cf71d04f095a670


[info] 
copyright = '''
Copyright © 2024 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order (top to bottom here)
# right-most subpack is enabled by default

[[subpack]]
define = "EXPERIMENTAL"
materials = ["RenderChunk"]
description = '''
§5 Experimental
Things that arent in other subpacks you will find here
'''

[[subpack]]
define = "HIGH_ROUNDED_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
§4High (rounded clouds)
Multilayer 16 steps Rounded Clouds, Folliage waves and Chunk Anim
'''

[[subpack]]
define = "HIGH_BOX_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
§4High (box clouds)
Multilayer Box Clouds, Chunk Anim, Folliage waves 
'''

[[subpack]]
define = "MEDIUM_BOX_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
§eMedium (box clouds)
Box Clouds and no folliage waves
'''

[[subpack]]
define = "MEDIUM_ROUNDED_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
§eMedium (rounded clouds)
Rounded Clouds and no folliage waves
'''

[[subpack]]
define = "LOWEST"
materials = ["RenderChunk"]
description = '''
§a Lowest
Soft clouds, disabled auroras, waves, fog, reflection, underwater streaks.
'''

[[subpack]]
define = "DEFAULT"
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]
description = '''
§aDefault
'''