name = "Newb X Santan"
version = [0, 15, 15]
min_supported_mc_version = [1, 21, 20]
description = '''
§c%w
§7- §aA Newb edit with spectacular colors and more subtle tweaks!
%v
https://discord.com/channels/844591537430069279/1301209950340518011
''' # %w = patch warning, %v = version
authors = ["raden1", "devendrn"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "95f774cf-4afa-73e7-a21a-72146307b1d2" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "LegacyCubemap", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]


[info] 
copyright = '''
Copyright (c) %a

**Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited.
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "EXPERIMENTAL"
materials = ["RenderChunk"]
description = '''
Things that arent in other subpacks you will find here
'''

[[subpack]]
define = "BOX_CLOUDS_NO_PLANT_WAVES"
materials = ["Clouds", "RenderChunk"]
description = '''
Box Clouds and no folliage waves
'''

[[subpack]]
define = "ROUNDED_CLOUDS_NO_PLANT_WAVES"
materials = ["Clouds", "RenderChunk"]
description = '''
Rounded Clouds and no folliage waves
'''

[[subpack]]
define = "UNOBTRUSIVE"
materials = ["RenderChunk"]
description = '''
Unobtrusive (more things removed than no wave and fog)
'''

[[subpack]]
define = "DOUBLE_ROUNDED_CLOUDS_AND_CHUNK_ANIM"
materials = ["Clouds", "RenderChunk"]
description = '''
Multilayer Rounded Clouds and Chunk Anim!!1! (also laggey)
'''

[[subpack]]
define = "DOUBLE_BOX_CLOUDS_AND_CHUNK_ANIM"
materials = ["Clouds", "RenderChunk"]
description = '''
Multilayer Box Clouds and Chunk Anim! (laggey)
'''

[[subpack]]
define = "BOX_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
Box Clouds
'''

[[subpack]]
define = "CHUNK_ANIM"
materials = ["RenderChunk"]
description = '''
Chunk loading animation
'''

[[subpack]]
define = "NO_WAVE_NO_FOG"
materials = ["RenderChunk"]
description = '''
No fog and wave effects
'''

[[subpack]]
define = "NO_FOG"
materials = ["RenderChunk"]
description = '''
No fog effect
'''

[[subpack]]
define = "NO_WAVE"
materials = ["RenderChunk"]
description = '''
No wave effects
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
'''