name = "Newb Santan Revitalized"
version = [0, 1, 1]
min_supported_mc_version = [1, 21, 20]
description = '''
§c%w
§7- §6Adding some clarity to MCBE graphics. §7|| §aA Newb variant focused on vivid colors and eye comfort
%v
§3https://devendrn.github.io/newb-shader/
''' # %w = patch warning, %v = version
authors = ["raden1", "devendrn"]
url = "https://github.com/KianSantan88/nx-santan-shader"
uuid = "2394270a-3eb8-45df-91db-472dc04904ce" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]

[info] 
copyright = '''
Copyright © 2024 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "EXPERIMENTAL"
materials = ["Clouds", "RenderChunk"]
description = '''
§5 Experimental
Things that arent in other subpacks you will find here
'''

[[subpack]]
define = "HIGH_ROUNDED_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
§4High (rounded clouds)
Multilayer 16 steps Rounded Clouds, Folliage waves and Chunk Anim
'''

[[subpack]]
define = "HIGH_BOX_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
§4High (box clouds)
Multilayer Box Clouds, Chunk Anim, Folliage waves 
'''

[[subpack]]
define = "MEDIUM_BOX_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
§eMedium (box clouds)
Box Clouds and no folliage waves
'''

[[subpack]]
define = "MEDIUM_ROUNDED_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
§eMedium (rounded clouds)
Rounded Clouds and no folliage waves
'''

[[subpack]]
define = "LOWEST"
materials = ["Clouds", "RenderChunk"]
description = '''
§a Lowest
Soft clouds, disabled auroras, waves, fog, reflection, underwater streaks, shimmer, leaks, galaxy, shooting stars.
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
'''
